Feature/style
zagz16/e-commerce pull request #3
Opened 2021-03-26 22:18 UTC by zagz16

созданы переменные и цвета + типография с миксинами

2021-03-26 22:21 UTC, ooonikpro commented
Проверь файл typography он почему-то пустой

2021-03-26 22:21 UTC, zagz16 commented
ок

2021-03-26 22:44 UTC, ooonikpro requested changes

2021-03-26 22:44 UTC, ooonikpro commented on colors.scss
> +$color-third-1:rgba(208, 168, 102, 1);
Бля...ну рили) масло масленное

2021-03-26 22:44 UTC, ooonikpro commented on colors.scss
> +$color-third-1:rgba(208, 168, 102, 1);
Давай лучше сделаем так:

$color-primary-%
$color-secondary-%
$color-addition-%
% - это цифра

2021-03-26 22:44 UTC, ooonikpro commented on colors.scss
> +$color-third-1:rgba(208, 168, 102, 1);
Хотя я бы попробовал эти цвета более осмысленно назвать. Ибо нихуя не понятно че за цвет используется

2021-03-26 22:44 UTC, ooonikpro commented on typography.scss
> +font-size: 32px;
не используй px
Лучше используй rem

32px = 3.2rem

2021-03-26 22:44 UTC, ooonikpro commented on typography.scss
> +font-size: 32px;
Потом надо будет добавить вот это в styles.scss

```scss
html {
    font-size: 62.5%;
}
```

2021-03-27 09:12 UTC, ooonikpro commented
Никита, тебе надо будет сделать ребейз (git rebase origin/main) и положить свои файлы в папку src/styles

2021-03-29 07:52 UTC, merged